filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/mylog/*.log

output.logstash:
  hosts: ["10.0.0.16:5044"]

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"