filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/mylog/*.log
  fields:
      source: Sakura-Test-63
      beat.hostname: my_host_name
  fields_under_root: true
output.logstash:
  hosts: ["10.0.0.16:5044"]

processors:
  - add_docker_metadata:
      host: "unix:///host_docker/docker.sock"